name: Build and Push Docker - awscli

on:
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    timeout-minutes: 180
    env:
      DOCKER_DRIVER: overlay2
      DOCKER_BUILDKIT: 1
    steps:
      - uses: actions/checkout@v3

      - name: Docker Login
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: all
          # image: tonistiigi/binfmt:qemu-v10.0.4-56 # ← 固定版本

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          install: true

      - name: Install make (if needed)
        run: |
          sudo apt-get update
          sudo apt-get install -y make

      - name: make .env file
        run: echo "BASIC_ENV=pro" > .env

      - name: Show Docker version
        run: docker --version

      # （若上面已登录，这里可省略二次登录；或者保留也无妨）
      # - name: Docker Login
      #   run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and Push Service
        run: make -C ./awscli buildx
