name: Build and Push Docker - awscli

on:
  workflow_dispatch: # 手动触发

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    timeout-minutes: 180 # 3小时超时
    env:
      DOCKER_DRIVER: overlay2
      DOCKER_BUILDKIT: 1
    steps:
      - uses: actions/checkout@v3

      # 1️⃣ 先注册 QEMU 多架构仿真
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: all

      # 2️⃣ 然后搭建 buildx builder（install: true 会自动关联 QEMU）
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          install: true

      - name: Install make (if needed)
        run: |
          sudo apt-get update
          sudo apt-get install -y make

      # - name: Copy .env file
      #   run: cp .env.pro .env

      - name: make .env file
        run: echo "BASIC_ENV=pro" > .env

      - name: Show Docker version
        run: docker --version

      - name: Docker Login
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and Push Service
        run: make -C ./awscli buildx
