name: Build and Push Docker - postgres

on:
  schedule:
    - cron: "0 0 * * 2,5"
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    timeout-minutes: 180 # 3小时超时
    env:
      # DOCKER_DRIVER: overlay2
      # DOCKER_BUILDKIT: 1
      BASIC_ENV: pro
    steps:
      - name: Checkout repository
        uses: actions/checkout@main

      - uses: docker/login-action@master
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@master

      # - name: make .env file
      #   run: echo "BASIC_ENV=pro" > .env

      - name: Build and Push Service
        run: make -C ./postgres buildx
