name: Build and Push Docker - ssh-debian

on:
  workflow_dispatch: # 手动触发

permissions:
  contents: read
  packages: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    timeout-minutes: 180 # 3小时超时
    env:
      DOCKER_DRIVER: overlay2
      DOCKER_BUILDKIT: 1
    steps:
      - name: Checkout repository
        uses: actions/checkout@main

      - uses: docker/login-action@master
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/setup-buildx-action@master

      - name: make .env file
        run: echo "BASIC_ENV=pro" > .env

      - name: Build and Push Service
        run: make -C ./ssh-debian buildx
