jobs:
  build-and-push:
    runs-on: ubuntu-latest
    env:
      DOCKER_DRIVER: overlay2
      DOCKER_BUILDKIT: 1

    steps:
      - uses: actions/checkout@v3

      # 1先注册 QEMU 多架构仿真
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: all

      # 2 然后搭建 buildx builder（install: true 会自动关联 QEMU）
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          install: true

      - name: Install make
        run: |
          sudo apt-get update && sudo apt-get install -y make

      - name: make .env file
        run: echo "BASIC_ENV=pro" > .env

      - name: Show Docker version
        run: docker --version

      - name: Docker Login
        run: echo "${{ secrets.DOCKER_PASSWORD }}" \
          | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and Push Service
        run: make -C ./awscli buildx
