# 文件路径：.github/workflows/run-shell.yml
name: Run Shell Script

# 手动触发
on:
  workflow_dispatch:

jobs:
  execute-shell:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@main

      - name: Set up environment
        run: |
          echo "Environment setup, e.g. install packages if needed"
          # sudo apt-get update && sudo apt-get install -y foo

      - name: make .env file
        run: echo "BASIC_ENV=pro" > .env

      - name: Make script executable
        run: chmod +x ./_migrate/docker_migrate.sh

      - name: Run shell script
        run: ./_migrate/docker_migrate.sh
