name: Run Shell Script migration3

on:
  schedule:
    - cron: "0 0 * * 2,5"
  workflow_dispatch:

permissions:
  contents: read
  packages: write

env:
  GHCR_OWNER: ${{ github.repository_owner }}

jobs:
  execute-shell:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@main

      - uses: docker/login-action@master
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Make script executable
        run: chmod +x ./_migrate/docker_migrate3.sh

      - name: Run shell script
        run: ./_migrate/docker_migrate3.sh
